apop2/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

app_name = 'apop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('survey/', include('survey.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('pwa.urls')),
    path('', HomeView.as_view(), name='home'),
]

survey/urls.py
from django.urls import path
from django.views.generic import TemplateView
from survey.views import SurveyListView, SurveyDetailView, SurveyFormView, UserSurveyListView

app_name = 'survey'

urlpatterns = [
    path('<int:pk>', SurveyFormView.as_view(), name='survey-detail'),
    path('<int:pk>/user/', UserSurveyListView.as_view(), name='user-survey-list'),
    path('', SurveyListView.as_view(), name='survey-list'),
]

survey/models/answer.py
from django.db import models


class Answer(models.Model):
    """Answer 모델 클래스
    Question에 대한 가능한 답변
    """    
    description = models.CharField(
        db_column='description',
        db_comment='description of answer',
        max_length=100,
        null=False,
        blank=False,
        help_text='질문 답변의 내용입니다.'
    )
    create_at = models.DateTimeField(
        db_column='create_at',
        db_comment='answer created time',
        auto_now_add=True,
        help_text='질문 답변의 생성 시간입니다.'
    )
    updated_at = models.DateTimeField(
        db_column='updated_at',
        db_comment='answer updated time',
        auto_now=True,
        help_text='질문 답변의 수정 시간입니다.'
    )

    class Meta:
        db_table = 'answer'
        verbose_name = '답변'
        verbose_name_plural = '답변'
        ordering = ['create_at']

    def __str__(self) -> str:
        """Answer 인스턴스 출력 메서드

        Returns:
            str: 답변의 내용
        """        
        return self.description

survey/models/question.py
from collections import namedtuple

from django.db import models

TYPE_FILED = namedtuple(
    "TYPE_FIELD", "text number radio select multi_select text_area"
)._make(range(6))


class Question(models.Model):
    """Question 모델 클래스
    Survey에서 수행해야 하는 질문
    """    
    TYPE_FILED = [
        (TYPE_FILED.text, "text"),
        (TYPE_FILED.number, "number"),
        (TYPE_FILED.radio, "radio"),
        (TYPE_FILED.select, "select"),
        (TYPE_FILED.multi_select, "multi_select"),
        (TYPE_FILED.text_area, "text_area"),
    ]
    title = models.CharField(
        db_column="title",
        db_comment="question title",
        null=False,
        blank=False,
        help_text="질문 제목",
        max_length=40
    )
    description = models.TextField(
        db_column="description",
        db_comment="question description",
        null=True,
        blank=False,
        help_text="질문 설명",
        max_length=100
    )
    create_at = models.DateTimeField(
        db_column="create_at",
        db_comment="question created time",
        auto_now_add=True,
        help_text="질문 생성 시간"
    )
    updated_at = models.DateTimeField(
        db_column="updated_at",
        db_comment="question updated time",
        auto_now=True,
        help_text="질문 수정 시간"
    )
    answers = models.ManyToManyField(
        to="Answer",
        through="QuestionAnswer",
        related_name="questions",
    )
    type_filed = models.PositiveSmallIntegerField(
        db_column="type_filed",
        db_comment="question type",
        null=False,
        choices=TYPE_FILED,
        help_text="질문 타입",
        default=2
    )

    class Meta:
        db_table = "question"
        verbose_name = "질문"
        verbose_name_plural = "질문"
        ordering = ["create_at"]

    def __str__(self) -> str:
        """Question 인스턴스 출력 메서드

        Returns:
            str: Question 제목
        """        
        return self.title

survey/models/question_answer.py
from django.db import models


class QuestionAnswer(models.Model):
    """Question과 Answer의 N:M관계 지원을 위한 모델 클래스
    """    
    question = models.ForeignKey(
        to="Question",
        db_comment="question",
        on_delete=models.CASCADE,
    )
    answer = models.ForeignKey(
        to="Answer",
        db_comment="answer",
        on_delete=models.CASCADE,
    )
    order = models.IntegerField(
        db_column="order",
        db_comment="answer order",
        null=False,
        blank=False,
        help_text="답변 순서"
    )

    class Meta:
        db_table = "question_answer"
        verbose_name = "질문 답변"
        verbose_name_plural = "질문 답변"
        ordering = ["question", "order"]

    @property
    def next_order(self) -> int:
        """가질 수 있는 다음 순서를 반환

        Returns:
            int: 기본적으로 마지막 순서 번호 + 1
        """        
        return QuestionAnswer.objects.filter(question=self.question).count() + 1

    def exist_order(self) -> bool:
        """현재 QuestionAnswer의 순서 번호가 이미 존재하는지 확인

        Returns:
            bool: 존재하면 True, 존재하지 않으면 False
        """        
        return QuestionAnswer.objects.filter(question=self.question, order=self.order).exists()

    def swap_order(self, order: int):
        """두 QuestionAnswer의 순서 번호를 교환

        Args:
            order (int): 교환하고 싶은 번호
        """        
        if order == self.order:
            return
        question_answer = QuestionAnswer.objects.get(
            question=self.question,
            order=order
        )
        question_answer.order, self.order = self.order, question_answer.order
        question_answer.save()
        self.save()

    def save(self, *args, **kwargs):
        """순서 번호 자동 설정을 위한 메서드
        """        
        if self.order is None:
            self.order = self.next_order
        if self.exist_order():
            QuestionAnswer.objects.filter(
                question=self.question,
                order=self.order
            ).update(
                order=self.next_order
            )

        super().save(*args, **kwargs)

survey/models/reply.py
from django.db import models


class Reply(models.Model):
    """Reply 모델 클래스
    UserSurvey와 SurveyQuestion에 대한 유저 응답
    """    
    user_survey = models.ForeignKey("UserSurvey", on_delete=models.CASCADE, related_name="replies")
    survey_question = models.ForeignKey("SurveyQuestion", on_delete=models.CASCADE, related_name="replies")
    content = models.CharField(
        db_column="content",
        db_comment="reply to question",
        null=False,
        blank=True,
        help_text="답변",
        max_length=255,
    )

    @property
    def title(self) -> str:
        return self.survey_question.question.title

    @property
    def order(self) -> int:
        return self.survey_question.order

    class Meta:
        db_table = "reply"
        verbose_name = "답변"
        verbose_name_plural = "답변"
        ordering = ["user_survey"]

    

survey/models/survey.py
from django.db import models
from django.conf import settings


class Survey(models.Model):
    """Survey 모델 클래스
    설문에 대한 정보
    """    
    title = models.CharField(
        db_column="title",
        db_comment="survey title",
        null=False,
        blank=False,
        help_text="설문지 제목",
        max_length=40
    )
    description = models.TextField(
        db_column="description",
        db_comment="survey description",
        null=False,
        blank=False,
        help_text="설문지 설명",
        max_length=100
    )
    created_at = models.DateTimeField(
        db_column="created_at",
        db_comment="survey created time",
        auto_now_add=True,
        help_text="설문지 생성 시간"
    )
    updated_at = models.DateTimeField(
        db_column="updated_at",
        db_comment="survey updated time",
        auto_now=True,
        help_text="설문지 수정 시간"
    )
    questions = models.ManyToManyField(
        to="Question",
        through="SurveyQuestion",
        related_name="surveys",
    )
    users = models.ManyToManyField(
        to=settings.AUTH_USER_MODEL,
        through="UserSurvey",
        related_name="surveys",
    )

    def __str__(self) -> str:
        """Survey 인스턴스 출력 메서드

        Returns:
            str: Survey 제목
        """        
        return self.title

    class Meta:
        db_table = "survey"
        verbose_name = "설문조사"
        verbose_name_plural = "설문조사"
        ordering = ["title", "created_at"]

survey/models/survey_question.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class SurveyQuestion(models.Model):
    """Question과 Survey의 N:M관계 지원을 위한 모델 클래스
    """    
    survey = models.ForeignKey(
        to="Survey",
        db_comment="survey",
        on_delete=models.CASCADE,
    )
    question = models.ForeignKey(
        to="Question",
        db_comment="question",
        on_delete=models.CASCADE,
    )
    order = models.IntegerField(
        db_column="order",
        db_comment="question order",
        null=False,
        blank=False,
        help_text="질문 순서",
        validators=[MinValueValidator(1)],
    )
    
    def __str__(self) -> str:
        """SurveyQuestion 인스턴스 출력 메서드

        Returns:
            str: Question 제목
        """        
        return self.question.title

    class Meta:
        db_table = "survey_question"
        verbose_name = "설문조사 질문"
        verbose_name_plural = "설문조사 질문"
        ordering = ["survey", "order"]

    @property
    def next_order(self) -> int:
        """가질 수 있는 다음 순서를 반환

        Returns:
            int: 기본적으로 마지막 순서 번호 + 1
        """        
        return SurveyQuestion.objects.filter(survey=self.survey).count() + 1

    def exist_order(self) -> bool:
        """현재 SurveyQuestion의 순서 번호가 이미 존재하는지 확인

        Returns:
            bool: 존재하면 True, 존재하지 않으면 False
        """   
        return SurveyQuestion.objects.filter(survey=self.survey, order=self.order).exists()

    def swap_order(self, order: int):
        """두 SurveyQuestion의 순서 번호를 교환

        Args:
            order (int): 교환하고 싶은 번호
        """        
        if order == self.order:
            return
        survey_question = SurveyQuestion.objects.get(
            survey=self.survey,
            order=order
        )
        survey_question.order, self.order = self.order, survey_question.order
        survey_question.save()
        self.save()

    def save(self, *args, **kwargs):
        """순서 번호 자동 설정을 위한 메서드
        """        
        if self.order is None:
            self.order = self.next_order
        if self.exist_order():
            SurveyQuestion.objects.filter(
                survey=self.survey,
                order=self.order
            ).update(
                order=self.next_order
            )

        super().save(*args, **kwargs)

survey/models/user_survey.py
from django.db import models
from django.conf import settings


class UserSurvey(models.Model):
    """UserSurvey 모델 클래스
    User가 같은 survey라도 여러 번 수행할 수 있으므로
    UserSurvey 테이블로 하나의 설문지 작성을 표현
    """    
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        db_column='user_id',
        db_comment='user id',
        null=False,
        blank=False,
        help_text='유저 id'
    )
    survey = models.ForeignKey(
        to='Survey',
        on_delete=models.CASCADE,
        db_column='survey_id',
        db_comment='survey id',
        null=False,
        blank=False,
        help_text='설문 id'
    )
    create_at = models.DateTimeField(
        db_column='create_at',
        db_comment='user survey created time',
        auto_now_add=True,
        help_text='유저 설문 생성 시간'
    )
    updated_at = models.DateTimeField(
        db_column='updated_at',
        db_comment='user survey updated time',
        auto_now=True,
        help_text='유저 설문 수정 시간'
    )

    class Meta:
        db_table = 'user_survey'
        verbose_name = '유저 설문'
        verbose_name_plural = '유저 설문'
        ordering = ['create_at']

    def replies(self) -> models.QuerySet:
        """설문지 인스턴스에 대한 응답들 반환

        Returns:
            models.QuerySet: 응답들
        """        
        return self.replies().all()

survey/forms/question_tabular_form.py
from django.forms import ModelForm, Select

from survey.models import SurveyQuestion


class QuestionTabularForm(ModelForm):
    class Meta:
        model = SurveyQuestion
        fields = ["title", "description", "type_filed"]
        widgets = {
            "title": TextInput(attrs={"class": "form-control"}),
            "description": TextInput(attrs={"class": "form-control"}),
            "type_filed": Select(attrs={"class": "form-control"}),
        }

survey/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from survey.models import Survey, Question, UserSurvey, Reply, SurveyQuestion
from django.views.generic.edit import ProcessFormView
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class MyLoginRequiredMixin(LoginRequiredMixin):
    login_url = "/accounts/login/"
    redirect_field_name = "redirect_to"

class SurveyListView(MyLoginRequiredMixin, ListView):
    """참여 가능한 설문 목록을 제공하는 클래스 기반 뷰
    """    
    template_name='survey/survey_list.html'
    model = Survey
    paginate_by = 5
    
    
class SurveyDetailView(MyLoginRequiredMixin, DetailView):
    """설문에 대한 구체적인 정보를 제공하는 클래스 기반 뷰
    TODO 구현예정
    """    
    template_name='survey/survey_detail.html'
    model=Survey
    

class UserSurveyListView(MyLoginRequiredMixin, ListView):
    """설문 작성 결과를 제공하는 클래스 기반 뷰
    """    
    template_name='survey/user_survey_list.html'
    
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        """survey 정보를 추가한 context_data 반환

        Returns:
            dict[str, Any]: context_data를 반환
        """        
        context = super().get_context_data(**kwargs)
        context['survey'] = Survey.objects.get(**kwargs)
        return context
    
    def get_queryset(self) -> QuerySet[UserSurvey]:
        """UserSurvey에 대한 object_list를 반환
        현재 로그인 된 User가 선택한 Survey에 대한 UserSurvey들을 반환
        Returns:
            QuerySet[UserSurvey]: UserSurvey들에 대한 쿼리셋
        """        
        survey = Survey.objects.get(**self.kwargs)
        queryset = UserSurvey.objects.filter(user=self.request.user, 
                                             survey=survey).order_by('create_at')
        return queryset
    
class SurveyFormView(MyLoginRequiredMixin, ProcessFormView):
    """설문조사 폼을 제공하는 클래스 기반 뷰
    """
    
    def _create_replies(self, user_survey, post_data):
        """응답들을 생성하기 위한 메서드

        Args:
            user_survey (UserSurvey): 유저가 실시한 설문조사(새로 만들어진)
            post_data (QueryDict): 폼으로 입력받은 데이터
        """        
        for key in post_data.keys():
            if not key.isdigit(): # for excepting csrf_token
                continue
            
            question = Question.objects.get(pk=int(key))
            survey_question = SurveyQuestion.objects.get(survey=user_survey.survey, 
                                                         question=question)
            Reply.objects.create(user_survey=user_survey,
                                 survey_question=survey_question,
                                 content=','.join(post_data.getlist(key)))

    def get(self, request, *args, **kwargs):
        """폼 입력 화면

        Args:
            request (HttpRequest): HttpRequest정보

        Returns:
            HttpResponse: 렌더링 된 입력 화면 HTML
        """        
        context = {'object': Survey.objects.get(**kwargs)}
        return render(request, 'survey/user_survey_form.html', context)
    
    def post(self, request, *args, **kwargs):
        """폼 제출 화면

        Args:
            request (HttpRequest): HttpRequest정보

        Returns:
            HttpResponse: 렌더링 된 완료 화면 HTML
        """        
        self._create_replies(UserSurvey.objects.create(user=request.user,
                                                       survey=Survey.objects.get(**kwargs)),
                             request.POST)
        
        return render(request, 'survey/survey_complete.html')
    
    def put(self, request, *args, **kwargs):
        """작성된 설문 수정 화면
        
        Args:
            request (HttpRequest): HttpRequest정보
        
        Returns:
            HttpResponse: 렌더링 된 완료 화면 HTML
        """        
        return render(request, 'survey/survey_complete.html')
    

templates/survey/survey_complete.html
{% extends 'base.html' %}
{% block content %}

<div class="container py-4">
    <div class="p-5 mb-4 bg-body-tertiary rounded-3">
        
        <h1 class="text-center display-5 fw-bold">
            <svg xmlns="http://www.w3.org/2000/svg" width="52" height="52" fill="currentColor" class="bi bi-check-circle" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05"/>
              </svg>
            제출 완료
        </h1>
        <p class="text-center fs-4">참여해 주셔서 감사합니다.</p>
    </div>
    <div class="row justify-content-center">
            <a href="{% url 'home' %}" class="btn btn-primary btn-lg text-center" tabindex="-1" role="button">돌아가기</a>
    </div>
</div>

{% endblock content %}

templates/survey/survey_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-4">
    <div class="p-5 mb-4 bg-body-tertiary rounded-3">
        <h1 class="display-5 fw-bold">{{ object.title }}</h1>
        <p class="fs-4">{{ object.description }}</p>
    </div>
    <form>
        {% for question in object.questions.all %}
            {% include 'survey/components/question.html' %}
        {% endfor %}
        <button type="submit" class="btn btn-primary mt-5">제출하기</button>
    </form>
</div>
{% endblock content %}

templates/survey/survey_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-4">
    <div class="p-5 mb-4 bg-body-tertiary rounded-3">
        <h1 class="text-center display-5 fw-bold">설문조사</h1>
        <p class="text-center fs-4">설문조사를 통해 연구를 도와주세요!</p>
    </div>
    {% for survey in object_list %}
    <div class="card mb-5">
        <div class="row g-0">
            <div class="col-md-2">
                <img src="" class="img-fluid rounded-start" alt="..."/>
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ survey.title }}</h5>
                    <p class="card-text">{{ survey.description }}</p>
                    <p class="card-text"><small class="text-body-secondary">마지막 수정날짜 - {{ survey.updated_at }}</small></p>
                </div>
            </div>
            <div class="col-md-2 align-self-center">
                <div class="d-grid gap-2 mx-auto">
                    <a class="btn btn-primary" href="{% url 'survey:survey-detail' survey.pk %}" role="button">작성하기</a>
                    <a class="btn btn-secondary" href="{% url 'survey:user-survey-list' survey.pk %}" role="button">목록보기</a>
                    {% if user.is_superuser %}
                        <a class="btn btn-danger" href="#" role="button">수정하기</a>
                    {% endif %}
                  </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/survey/user_survey_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-4">
    <div class="p-5 mb-4 bg-body-tertiary rounded-3">
        <h1 class="display-5 fw-bold">{{ object.title }}</h1>
        <p class="fs-4">{{ object.description }}</p>
    </div>
    <form method="post">
        {% csrf_token %}
        {% for question in object.questions.all %}
            {% include 'survey/components/question.html' %}
        {% endfor %}
        <button type="submit" class="btn btn-primary mt-5">제출하기</button>
    </form>
</div>
{% endblock content %}

templates/survey/user_survey_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container py-4">
    <h1>{{ survey.title }}</h1>
    <div class="accordion" id="accordionUserSurvey">
        {% for user_survey in object_list %}
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button" type="button" data-bs-toggle="collapse"
                    data-bs-target="#{{ user_survey.pk }}" aria-expanded="true" aria-controls="{{ user_survey.pk }}">
                    {{ user_survey.create_at }}
                </button>
            </h2>
            <div id="{{ user_survey.pk }}" class="accordion-collapse collapse show"
                data-bs-parent="#accordionUserSurvey">
                <div class="accordion-body">
                    {% for reply in user_survey.replies.all %}
                        <p>
                            <mark>{{ reply.title }}</mark>
                            <br>
                            <small>{{ reply.content }}</small>
                        </p> 
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}