accounts/urls.py
from django.urls import path
from .views import HealthDataCsvDownloadAPIView, HealthDataCsvDownloadView, LoginView, LogoutView, SignUpView, SuccessSignUpView, UserHealthDataSyncView, UserHealthNoteUpdateView, UserInfoView, UserManageView, UserNoteUpdateView, UserPrimaryKeyAPIView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('successSignup/', SuccessSignUpView.as_view(), name='successSignup'),
    path('manage/', UserManageView.as_view(), name='userManage'),
    path('info/<int:pk>/', UserInfoView.as_view(), name='userInfo'),
    path('heatlhInfo/<int:pk>/', UserHealthNoteUpdateView.as_view(), name='userHealthInfo'),
    path('<int:pk>/updateNote/', UserNoteUpdateView.as_view(), name='updateNote'),
    path('<int:pk>/syncData/', UserHealthDataSyncView.as_view(), name='syncHealth'),
    path('<int:pk>/csvData/', HealthDataCsvDownloadView.as_view(), name='csvDownload'),
    path('users/<int:pk>/healthData.csv', HealthDataCsvDownloadAPIView.as_view(), name='csvDownloadApi'),
    path('users.csv', UserPrimaryKeyAPIView.as_view(), name="usersCsvDownloadApi")
]

apop2/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

app_name = 'apop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('survey/', include('survey.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('pwa.urls')),
    path('', HomeView.as_view(), name='home'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

class MyAuthenticationForm(UserCreationForm):
    last_name = forms.CharField(max_length=20, required=True, help_text='성을 입력해 주세요.', label='성')
    first_name = forms.CharField(max_length=20, required=True, help_text='이름을 입력해 주세요.', label='이름')

accounts/views.py
import csv
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.views import LoginView as Login, LogoutView as Logout
from django.views.generic import View, TemplateView, ListView, DetailView
from django.urls import reverse_lazy
from accounts.utils import make_csv_response
from huami.forms import HuamiAccountCreationForm
from huami.models.healthdata import HealthData
from .forms import MyAuthenticationForm
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib import messages
from huami.models import HuamiAccount

# Create your views here.
class LoginView(Login):
    """로그인을 위한 클래스 기반 뷰
    """    
    template_name = 'accounts/login.html'
    redirect_field_name = 'redirect_to'
    next_page= reverse_lazy('home')

    
class LogoutView(Logout):
    """로그아웃을 위한 클래스 기반 뷰
    """    
    template_name = 'accounts/login.html'
    redirect_field_name = 'redirect_to'
    next_page = reverse_lazy('home')


class SignUpView(View):
    """회원가입 페이지를 제공하는 클래스 기반 뷰
    """    
    form_class = [HuamiAccountCreationForm, MyAuthenticationForm]
    template_name = 'accounts/signup.html'
    
    def get(self, request, *args, **kwargs):
        """회원가입 폼 입력 화면

        Args:
            request (HttpRequest): HttpRequest 정보

        Returns:
            HttpResponse: 렌더링 된 입력화면 HTML
        """        
        account_form = self.form_class[1]
        huami_account_form = self.form_class[0]
        return render(request, self.template_name, {'account_form': account_form,
                                                    'huami_account_form': huami_account_form})
    
    def post(self, request, *args, **kwargs):
        """회원가입 폼 제출 화면

        Args:
            request (HttpRequest): HttpRequest 정보

        Returns:
            HttpResponse: 입력에 따라 렌러딩 된 결과화면 HTML
        """        
        account_form = self.form_class[1](request.POST)
        huami_account_form = self.form_class[0](request.POST)
        
        #HuamiAccountCreationForm에서 계정 정보가 유효한지 검증
        if account_form.is_valid() and huami_account_form.is_valid():
            user = account_form.save()
            huami_account = huami_account_form.save(commit=False)
            huami_account.user = user
            huami_account.save()
            
            return redirect('accounts:successSignup')

        return render(request, self.template_name, {'account_form': account_form, 
                                                    'huami_account_form': huami_account_form})
        

class SuccessSignUpView(TemplateView):
    """회원가입 성공 화면 제공을 위한 클래스 기반 뷰
    """    
    template_name = 'accounts/successSignup.html'


class SuperuserRequiredMixin(UserPassesTestMixin):
    """관리자만 접근하도록 지정하는 믹스인
    """    
    def test_func(self):
        return self.request.user.is_superuser
    

class UserInfoView(SuperuserRequiredMixin, DetailView):
    """유저 정보를 제공하기 위한 클래스 기반 뷰
    """
    model = get_user_model()
    context_object_name = 'userInfo'
    template_name = 'accounts/userInfo.html'
    

class UserManageView(SuperuserRequiredMixin, ListView):
    """유저 정보들을 리스트로 제공하기 위한 클래스 기반 뷰
    """    
    template_name = 'accounts/userManage.html'
    model = settings.AUTH_USER_MODEL
    context_object_name = 'users'
    queryset = get_user_model().objects.filter(is_superuser=False)
    paginate_by = 5


class UserNoteUpdateView(SuperuserRequiredMixin, View):
    """유저에 대한 비고란을 수정하기 위한 클래스 기반 뷰
    post요청만 지원
    """
    def post(self, request, pk):
        user = get_object_or_404(get_user_model(), pk=pk)
        user.huami.note = request.POST['note']
        user.huami.save()
        return redirect(reverse_lazy('accounts:userInfo', kwargs={'pk': pk}))


class UserHealthNoteUpdateView(SuperuserRequiredMixin, View):
    """유저가 가진 건강 정보의 비고란을 수정하기 위한 클래스 기반 뷰
    post요청만 지원
    """    
    def post(self, request, pk):
        health_data = get_object_or_404(HealthData, pk=pk)
        health_data.note = request.POST['note']
        health_data.save()
        return redirect(reverse_lazy('accounts:userInfo', kwargs={'pk': health_data.huami_account.user.pk}))

class UserHealthDataSyncView(SuperuserRequiredMixin, View):
    """유저의 데이터 동기화를 위한 클래스 기반 뷰
    get요청만 지원
    """    
    def get(self, request, pk):
        user = get_object_or_404(get_user_model(), pk=pk)
        try:
            health_data = HealthData.create_from_sync_data(user.huami)
            messages.success(request, f"{len(health_data)}일의 데이터가 추가되었습니다.")
        except Exception as e:
            messages.error(request, "동기화 과정 중 오류가 발생하였습니다.")
            
        return redirect(reverse_lazy('accounts:userInfo', kwargs={'pk': pk}))
    

class HealthDataCsvDownloadView(SuperuserRequiredMixin, View):
    """유저 데이터를 csv로 전달하는 클래스 기반 뷰
    get요청만 지원
    """    
    def get(self, request, pk):
        user = get_object_or_404(get_user_model(), pk=pk)
        response = HttpResponse(headers={
            'Content-Type':'text/csv',
            'Content-Disposition': f'attachment; filename="{pk}.csv"'})
        
        return make_csv_response(user, response)
    

class AuthKeyRequiredMixin(UserPassesTestMixin):
    """headers에 auth-key가 존재하는지 여부 확인
    """    
    def test_func(self):
        return self.request.headers.get('auth-key') == settings.AUTH_KEY
    
    def handle_no_permission(self):
        return HttpResponse("You have not permission")

class HealthDataCsvDownloadAPIView(AuthKeyRequiredMixin, View):
    """데이터를 가져올 유저의 pk를 리스트로 받아서 해당하는 유저들의 데이터를 csv파일로 전달하는 API 클래스 기반 뷰
    get 요청만 지원
    """    
    def get(self, request: HttpRequest, pk: int):
        if get_user_model().objects.filter(pk=pk).exists() == False:
            return HttpResponse("No person in users")
        
        user = get_object_or_404(get_user_model(), pk=pk)
        
        if HuamiAccount.objects.filter(user=user).exists() == False:
            return HttpResponse("No huami account in user")
        
        response = HttpResponse(headers={
            'Content-Type':'text/csv',
            'Content-Disposition': f'attachment; filename="{pk}.csv"'})

        return make_csv_response(user, response)
    
class UserPrimaryKeyAPIView(AuthKeyRequiredMixin, View):
    """일반유저들의 이름과 대응하는 PK를 전달하는 API 클래스 기반 뷰
    get 요청만 지원
    """    
    def get(self, request: HttpRequest):
        response = HttpResponse(headers={
            'Content-Type':'text/csv',
            'Content-Disposition': f'attachment; filename="users.csv"'})
        
        file = csv.writer(response)
        head_line = []
        if request.headers.get('fullname') == 'True':
            head_line.append('fullname')
        head_line.append('pk')
        file.writerow(head_line)
        
        for user in get_user_model().objects.filter(is_superuser=False).all():
            line = []
            if request.headers.get('fullname') == 'True':
                line.append(user.huami.full_name)
            line.append(user.pk)
            file.writerow(line)
        
        return response
    

templates/accounts/base.html
{# Load the tag library #}
{% load django_bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% load static %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>중견연구</title>
  </head>

  <body>
    {% block content %}
    {% endblock content %}
  </body>

</html>

templates/accounts/login.html
{% extends 'accounts/base.html' %}
{# Load the tag library #}
{% load django_bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% load static %}

{% block content %}
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">
              <form method="post" class="form">
                {% csrf_token %}
                <h2 class="fw-bold mb-2 text-uppercase">중견연구</h2>
                <p class="text-white-50 mb-5">로그인 정보를 입력해주세요!</p>
                {% bootstrap_form form %}
                <button class="btn btn-outline-light btn-lg px-5" type="submit">로그인하기</button>
              </form>
            </div>
            <div>
              <p class="mb-0"><a href="{% url 'accounts:signup' %}" class="text-white-50 fw-bold">회원가입</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/accounts/signup.html
{% extends 'accounts/base.html' %}

{# Load the tag library #}
{% load django_bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% load static %}

{% block content %}
<section class="h-100 h-custom gradient-custom-2">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12">
        <form method="post" class="form">
          {% csrf_token %}
          <div class="card card-registration card-registration-2" style="border-radius: 15px;">
            <div class="card-body p-0">
              <div class="row g-0">
                <div class="col-lg-6">
                  <div class="p-5">
                    <h3 class="fw-normal mb-5" style="color: #140e3a;">회원가입 정보를 입력해주세요.</h3>
                    {% bootstrap_form account_form %}
                  </div>
                </div>
                <div class="col-lg-6 bg-indigo text-white">
                  <div class="p-5">
                    {% bootstrap_form huami_account_form %}
                    <div class="form-check d-flex justify-content-start mb-4 pb-3">
                      <input class="form-check-input me-3" type="checkbox" value="" id="form2Example3c" required />
                      <label class="form-check-label text-black" for="form2Example3">
                        <a href="#!" class="text-black"><u>정보 이용 약관</u></a> 에 동의합니다.
                      </label>
                    </div>
                    <button type="submit" class="btn btn-light btn-lg" data-mdb-ripple-color="dark">회원가입</button>
                    <a class="btn btn-secondary" href="{% url 'home' %}" role="button">홈으로</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/accounts/successSignup.html
{% extends 'accounts/base.html' %}

{# Load the tag library #}
{% load django_bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% load static %}

{% block content %}
<section class="h-100 h-custom gradient-custom-2">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-6">
          <div class="card card-registration card-registration-2" style="border-radius: 15px;">
            <div class="card-body p-0">
              <div class="row g-0">
                <div class="col-lg-12">
                  <div class="p-5 text-center">
                    <h3 class="fw-normal mb-5" style="color: #140e3a;">회원 가입이 완료되었습니다.</h3>
                    <p class="lead">관리자의 요청을 수행해주세요.</p>
                    <div class="p-5 text-center">
                      <a class="btn btn-secondary" href="{% url 'accounts:login' %}" role="button">로그인</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/accounts/userInfo.html
{% extends 'base.html' %}
{% block content %}
<div class="container py-4">
    <div class="card">
        <div class="card-body">
            <div class="d-flex w-100 justify-content-between">
                <h3 class="card-title">{{ userInfo.huami.full_name }}</h3>
                <small>마지막 동기화: {{ userInfo.huami.sync_date }}</small>
            </div>
            <div class="row">
                <label for="userId" class="col-sm-2 col-form-label">유저아이디</label>
                <div class="col-sm-4">
                    <input type="text" readonly class="form-control-plaintext" id="userId"
                        value="{{ userInfo.username }}">
                </div>
                <label for="email" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-4">
                    <input type="text" readonly class="form-control-plaintext" id="email"
                        value="{{ userInfo.huami.email }}">
                </div>
                <hr>
            </div>

            <form action="{% url 'accounts:updateNote' userInfo.pk %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="note">참고사항</label>
                    <textarea class="form-control" id="note" rows="5" name="note">{{ userInfo.huami.note }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary mt-2">수정하기</button>
            </form>
            <hr>
            
            <div class="d-flex w-100 justify-content-between">
              <div>
                <h4>데이터 수집 현황</h4>
                <a href="{% url 'accounts:csvDownload' userInfo.pk %}" class="btn btn-secondary">CSV로 저장</a>
              </div>
              <form action="{% url 'accounts:syncHealth' userInfo.pk %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-secondary">동기화</button>
              </form>
            </div>
           
            <table class="table text-center">
                <thead>
                  <tr>
                    <th scope="col">날짜</th>
                    <th scope="col">심박수, 수면질, 걸음수</th>
                    <th scope="col">스트레스</th>
                    <th scope="col">산소포화도</th>
                    <th scope="col">비고</th>
                  </tr>
                </thead>
                <tbody>
                  {% for health in userInfo.huami.health.all %}
                    <tr>
                      <th scope="col">{{ health.date }}</th>
                      <td scope="col">
                        {% if health.heart_rate != None %}
                          O
                        {% else %}
                          X
                        {% endif %}
                      </td>
                      <td scope="col">
                        {% if health.stress != None %}
                          O
                        {% else %}
                          X
                        {% endif %}
                      </td>
                      <td scope="col">
                        {% if health.spo2 != None %}
                          O
                        {% else %}
                          X
                        {% endif %}
                      </td>
                      <td scope="col">
                        <form action="{% url 'accounts:userHealthInfo' health.pk %}" method="post">
                          {% csrf_token %}
                          <div class="row">
                            <div class="col-10">

                              <div class="form-group">
                                  <textarea class="form-control" id="note" rows="3" name="note">{{ health.note }}</textarea>
                              </div>
                            </div>
                            <div class="col-2">
                              <button type="submit" class="btn btn-primary mt-2">수정하기</button>  

                            </div>
                          </div>
                      </form>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>
    </div>

</div>
{% endblock %}

templates/accounts/userManage.html
{% extends 'base.html' %}
{% block content %}

<div class="container py-4">
    <div class="list-group mb-4">
        {% for user in users %}
        <a href="{% url 'accounts:userInfo' user.pk %}" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ user.huami.full_name }}</h5>
            </div>
            <p class="mb-1">{{ user.huami.note }}</p>
            <small>마지막 동기화: {{ user.huami.sync_date }}</small>
        </a>
        {% endfor %}
    </div>
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo; 처음으로</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전</a>
            </li>
            {% endif %}
            {% for page_num in page_obj.page_range %}
            <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">다음</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">마지막으로 &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
</div>

{% endblock content %}